// The web app's only view of the API (CLAUDE.md: apps/web imports this package, never apps/api).
// schema.ts and ../openapi.json are generated by `pnpm contract`; never edit them by hand.
import type { components } from './schema';

export type { components, operations, paths } from './schema';

export type Exercise = components['schemas']['Exercise'];
export type Me = components['schemas']['Me'];
export type Problem = components['schemas']['Problem'];
