// The web app's only view of the API (CLAUDE.md: apps/web imports this package, never apps/api).
// schema.ts and ../openapi.json are generated by `pnpm contract`; never edit them by hand.
import type { components, paths } from './schema';

export type { components, operations, paths } from './schema';

export type Equipment = components['schemas']['Equipment'];
export type Exercise = components['schemas']['Exercise'];
export type LastTime = components['schemas']['LastTime'];
export type Me = components['schemas']['Me'];
export type Problem = components['schemas']['Problem'];
export type Profile = components['schemas']['Profile'];
export type Routine = components['schemas']['Routine'];
export type RoutineSlot = components['schemas']['RoutineSlot'];
export type SetRow = components['schemas']['SetRow'];
export type Suggestion = components['schemas']['Suggestion'];
export type SyncBatch = components['schemas']['SyncBatch'];
export type SyncDeletion = components['schemas']['SyncDeletion'];
export type SyncResult = components['schemas']['SyncResult'];
export type WeightUnit = components['schemas']['WeightUnit'];
export type WorkoutExerciseRow = components['schemas']['WorkoutExerciseRow'];
export type WorkoutRow = components['schemas']['WorkoutRow'];

/**
 * The header names a GET's success response declares, without the index signature every one
 * carries. A path with no GET declares none.
 */
type DeclaredHeaders<Path extends keyof paths> = paths[Path] extends {
  get: { responses: { 200: { headers: infer Headers } } };
}
  ? keyof { [Name in keyof Headers as string extends Name ? never : Name]: never }
  : never;

/**
 * The response header naming the account a member answer belongs to. A client keeps the body only
 * for the account it names (docs/08 §5). Checked here against the headers the generated contract
 * declares on each member route's success response.
 */
export const ACCOUNT_HEADER =
  'Overload-User' satisfies DeclaredHeaders<'/api/me'> satisfies DeclaredHeaders<'/api/exercises'> satisfies DeclaredHeaders<'/api/routines'>;
