// The web app's only view of the API (CLAUDE.md: apps/web imports this package, never apps/api).
// schema.ts and ../openapi.json are generated by `pnpm contract`; never edit them by hand.
import type { components, paths } from './schema';

export type { components, operations, paths } from './schema';

export type Exercise = components['schemas']['Exercise'];
export type Me = components['schemas']['Me'];
export type Problem = components['schemas']['Problem'];

/**
 * The response header naming the account a member answer belongs to. A client keeps the body only
 * for the account it names (docs/08 §5). Checked here against the generated contract.
 */
export const ACCOUNT_HEADER =
  'Overload-User' satisfies keyof paths['/api/me']['get']['responses'][200]['headers'];
