/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness. Answers without touching the database */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The function is running */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Health'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The signed-in user, their profile, and whether they are the admin */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The caller */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Me'];
          };
        };
        /** @description No session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['Problem'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/exercises': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Seeded exercises plus the caller’s own, with the caller’s effective settings, by name */
    get: {
      parameters: {
        query?: {
          /** @description Include exercises the caller has hidden. Default `false`. */
          includeHidden?: 'true' | 'false';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The library */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ExerciseList'];
          };
        };
        /** @description A query parameter of the wrong type */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['Problem'];
          };
        };
        /** @description No session */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/problem+json': components['schemas']['Problem'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      /** @enum {string} */
      status: 'ok';
    };
    Me: {
      user: {
        /**
         * Format: uuid
         * @example 0192a001-7c1e-7a33-9c2d-4b6f1e0a9d11
         */
        id: string;
        name: string;
        /** Format: email */
        email: string;
        image: string | null;
      };
      isAdmin: boolean;
      profile: components['schemas']['Profile'];
    };
    /** @description Null until the user has set one up. */
    Profile: {
      /** @example Asia/Tokyo */
      timezone: string;
      heightCm: number | null;
      /** @enum {string|null} */
      sex: 'male' | 'female' | null;
      /** Format: date */
      birthDate: string | null;
      /** @description ISO weekdays, 1 = Monday. */
      trainingWeekdays: number[];
    } | null;
    Problem: {
      /** @example urn:overload:problem:unauthenticated */
      type: string;
      title: string;
      status: number;
      detail?: string;
      /** @description Stable and machine-readable. Clients switch on this. */
      code: string;
      requestId: string;
      /** @description Present only for `validation_failed`. */
      errors?: {
        path: string;
        message: string;
      }[];
    };
    ExerciseList: {
      items: components['schemas']['Exercise'][];
    };
    Exercise: {
      /**
       * Format: uuid
       * @example 0192a001-7c1e-7a33-9c2d-4b6f1e0a9d11
       */
      id: string;
      /** @example Barbell Bench Press */
      name: string;
      equipment: components['schemas']['Equipment'];
      /** @description True for the caller’s own exercise, false for a seeded one. */
      custom: boolean;
      hidden: boolean;
      /** @example 2.5 */
      incrementKg: number;
      /** @example 180 */
      restSeconds: number;
      /** @example 6 */
      repLow: number;
      /** @example 10 */
      repHigh: number;
      /** @description Which values are the caller’s own settings rather than defaults. */
      overrides: {
        incrementKg: boolean;
        restSeconds: boolean;
        repLow: boolean;
        repHigh: boolean;
      };
    };
    /**
     * @description A load-increment class, not an equipment inventory (docs/04 `exercise`).
     * @enum {string}
     */
    Equipment:
      | 'barbell'
      | 'dumbbell'
      | 'machine_plate'
      | 'machine_stack'
      | 'cable'
      | 'bodyweight'
      | 'other';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
