-- migrate:up

-- Generated by apps/api/seed/exercises.ts. Do not edit by hand; a correction is a new migration.

INSERT INTO exercise
  (name, equipment, default_increment_kg, default_rest_seconds, default_rep_low, default_rep_high)
VALUES
  ('Barbell Back Squat', 'barbell', 2.50, 180, 6, 10),
  ('Barbell Front Squat', 'barbell', 2.50, 180, 6, 10),
  ('Barbell Deadlift', 'barbell', 2.50, 180, 6, 10),
  ('Barbell Romanian Deadlift', 'barbell', 2.50, 180, 6, 10),
  ('Barbell Bench Press', 'barbell', 2.50, 180, 6, 10),
  ('Incline Barbell Bench Press', 'barbell', 2.50, 180, 6, 10),
  ('Close Grip Barbell Bench Press', 'barbell', 2.50, 120, 6, 10),
  ('Barbell Overhead Press', 'barbell', 2.50, 180, 6, 10),
  ('Bent Over Barbell Row', 'barbell', 2.50, 180, 6, 10),
  ('Barbell Hip Thrust', 'barbell', 2.50, 120, 6, 10),
  ('Barbell Curl', 'barbell', 2.50, 90, 10, 15),
  ('Lying EZ Bar Triceps Extension', 'barbell', 2.50, 90, 10, 15),
  ('Dumbbell Bench Press', 'dumbbell', 1.00, 120, 6, 10),
  ('Incline Dumbbell Bench Press', 'dumbbell', 1.00, 120, 6, 10),
  ('Seated Dumbbell Shoulder Press', 'dumbbell', 1.00, 120, 6, 10),
  ('1 Arm Dumbbell Row', 'dumbbell', 1.00, 120, 6, 10),
  ('Dumbbell Romanian Deadlift', 'dumbbell', 1.00, 120, 6, 10),
  ('Walking Dumbbell Lunge', 'dumbbell', 1.00, 120, 6, 10),
  ('Bulgarian Dumbbell Split Squat', 'dumbbell', 1.00, 120, 6, 10),
  ('Dumbbell Goblet Squat', 'dumbbell', 1.00, 120, 6, 10),
  ('Dumbbell Lateral Raise', 'dumbbell', 1.00, 90, 10, 15),
  ('Dumbbell Rear Delt Fly', 'dumbbell', 1.00, 90, 10, 15),
  ('Dumbbell Fly', 'dumbbell', 1.00, 90, 10, 15),
  ('Dumbbell Curl', 'dumbbell', 1.00, 90, 10, 15),
  ('Dumbbell Hammer Curl', 'dumbbell', 1.00, 90, 10, 15),
  ('Overhead Dumbbell Triceps Extension', 'dumbbell', 1.00, 90, 10, 15),
  ('Machine Chest Press', 'machine_stack', 5.00, 120, 6, 10),
  ('Machine Shoulder Press', 'machine_stack', 5.00, 120, 6, 10),
  ('Chest Supported Machine Row', 'machine_stack', 5.00, 120, 6, 10),
  ('Machine Chest Fly', 'machine_stack', 5.00, 90, 10, 15),
  ('Machine Rear Delt Fly', 'machine_stack', 5.00, 90, 10, 15),
  ('Machine Leg Extension', 'machine_stack', 5.00, 90, 10, 15),
  ('Seated Machine Leg Curl', 'machine_stack', 5.00, 90, 10, 15),
  ('Lying Machine Leg Curl', 'machine_stack', 5.00, 90, 10, 15),
  ('Plate-Loaded Leg Press', 'machine_plate', 2.50, 120, 6, 10),
  ('Plate-Loaded Hack Squat', 'machine_plate', 2.50, 120, 6, 10),
  ('Plate-Loaded Chest Press', 'machine_plate', 2.50, 120, 6, 10),
  ('Plate-Loaded Row', 'machine_plate', 2.50, 120, 6, 10),
  ('Standing Plate-Loaded Calf Raise', 'machine_plate', 2.50, 90, 10, 15),
  ('Cable Lat Pulldown', 'cable', 2.50, 120, 6, 10),
  ('Seated Cable Row', 'cable', 2.50, 120, 6, 10),
  ('Cable Triceps Pushdown', 'cable', 2.50, 90, 10, 15),
  ('Overhead Cable Triceps Extension', 'cable', 2.50, 90, 10, 15),
  ('1 Arm Cable Lateral Raise', 'cable', 2.50, 90, 10, 15),
  ('Cable Face Pull', 'cable', 2.50, 90, 10, 15),
  ('Cable Chest Fly', 'cable', 2.50, 90, 10, 15),
  ('Pull-Up', 'bodyweight', 0.00, 120, 6, 10),
  ('Chin-Up', 'bodyweight', 0.00, 120, 6, 10),
  ('Parallel Bar Dip', 'bodyweight', 0.00, 120, 6, 10),
  ('Hanging Leg Raise', 'bodyweight', 0.00, 90, 10, 15);

-- migrate:down

DELETE FROM exercise WHERE owner_user_id IS NULL;
