/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface AuditEvent {
  action: string;
  actorUserId: string | null;
  detail: Json | null;
  id: Generated<string>;
  ip: string | null;
  occurredAt: Generated<Timestamp>;
  targetId: string | null;
  targetType: string | null;
  userAgent: string | null;
}

export interface Exercise {
  createdAt: Generated<Timestamp>;
  defaultIncrementKg: Generated<Numeric>;
  defaultRepHigh: Generated<number>;
  defaultRepLow: Generated<number>;
  defaultRestSeconds: Generated<number>;
  equipment: string;
  id: Generated<string>;
  name: string;
  ownerUserId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface ExerciseSetting {
  createdAt: Generated<Timestamp>;
  exerciseId: string;
  hiddenAt: Timestamp | null;
  incrementKg: Numeric | null;
  repHigh: number | null;
  repLow: number | null;
  restSeconds: number | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Invite {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  invitedByUserId: string | null;
  note: string | null;
  revokedAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
}

export interface RateLimit {
  count: number;
  id: Generated<string>;
  key: string;
  lastRequest: Int8;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserProfile {
  birthDate: Timestamp | null;
  createdAt: Generated<Timestamp>;
  heightCm: Numeric | null;
  sex: string | null;
  timezone: Generated<string>;
  trainingWeekdays: Generated<number[]>;
  updatedAt: Generated<Timestamp>;
  userId: string;
  weightUnit: Generated<string>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  auditEvent: AuditEvent;
  exercise: Exercise;
  exerciseSetting: ExerciseSetting;
  invite: Invite;
  rateLimit: RateLimit;
  session: Session;
  user: User;
  userProfile: UserProfile;
  verification: Verification;
}
