#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=14

# Captured values live in a gitignored scratch file so a re-run can resume.
# SECRETS ARE NEVER WRITTEN THERE — role passwords, client secrets and signing
# keys are generated or typed, shown once, and go straight into Vercel.
ENV_FILE=".provision.local"

# gen N — a URL-safe random string of N characters. 32 chars of [A-Za-z0-9] is
# ~190 bits, well past Neon's 60-bit minimum, and contains nothing that would
# break a connection string.
gen() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-32}"; printf '\n'; }

# secret_line NAME VALUE — show a value to copy into a dashboard. Not persisted.
secret_line() { printf '    %s%-24s%s %s\n' "$BOLD" "$1" "$RESET" "$2"; }

banner "Overload — provision staging and production"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before we start"
say "This provisions everything slice 1 needs: one Neon project with two"
say "branches, two Vercel projects, Google sign-in, and Sentry."
say ""
warn "Order matters in two places, and the wizard will stop you at both:"
note "  · the staging branch is created BEFORE the roles exist — Neon copies a"
note "    parent branch's roles AND passwords into a child at creation"
note "  · Deployment Protection goes to None on both Vercel projects, or the"
note "    rewrite, Health Auto Export and the iPhone checklist all break"
say ""
say "Role passwords are generated here, shown once, and typed into Vercel."
say "They are not written to any file. Keep this terminal open throughout."
say ""
if [[ ! -f docs/12-deployment-devops.md ]]; then
  warn "run this from the repo root: bash scripts/provision.sh"
  exit 1
fi
command -v gh >/dev/null 2>&1 || SKIPPED+=("GitHub CLI missing — the backup secret in stage 13")
note "Reference: docs/12 §2 (every variable), docs/13 §5 (the roles)."
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon — create the project"
open_url "https://console.neon.tech/app/projects"
step "New Project."
step "Name: overload"
step "Postgres version: 18"
step "Region: AWS Asia Pacific (Singapore) — aws-ap-southeast-1"
step "Create. The default branch is called 'main'; leave it that way."
say ""
say "On the project dashboard, open the connection details for branch 'main'."
step "Copy the hostname from the POOLED connection string (it ends in -pooler)."
ask NEON_MAIN_POOLED_HOST "main pooled host:"
step "Switch the toggle to the DIRECT connection and copy that hostname."
ask NEON_MAIN_DIRECT_HOST "main direct host:"
step "Copy the database name (usually 'neondb')."
ask NEON_DB "database name:"
write_env NEON_MAIN_POOLED_HOST "$NEON_MAIN_POOLED_HOST"
write_env NEON_MAIN_DIRECT_HOST "$NEON_MAIN_DIRECT_HOST"
write_env NEON_DB "$NEON_DB"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Neon — branch staging BEFORE the roles exist"
warn "This is the ordering trap. Do it now, before stage 5."
say "A child branch copies its parent's roles and their passwords. Branch first"
say "and bootstrap each branch separately, so a leaked staging password is not"
say "production's."
open_url "https://console.neon.tech/app/projects"
step "Branches → New Branch."
step "Name: staging.  Parent: main.  Include data up to: now."
step "Create."
say ""
say "Open the connection details for branch 'staging'."
step "Copy the POOLED hostname (ends in -pooler)."
ask NEON_STAGING_POOLED_HOST "staging pooled host:"
step "Copy the DIRECT hostname."
ask NEON_STAGING_DIRECT_HOST "staging direct host:"
write_env NEON_STAGING_POOLED_HOST "$NEON_STAGING_POOLED_HOST"
write_env NEON_STAGING_DIRECT_HOST "$NEON_STAGING_DIRECT_HOST"
confirm "Confirm: 'staging' exists and NO overload_* role has been created yet." \
  || { warn "Stop here. Delete the staging branch, then re-run from stage 3."; exit 1; }

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Generate the six role passwords"
MAIN_OWNER_PW=$(gen 32);    MAIN_APP_PW=$(gen 32);    MAIN_BACKUP_PW=$(gen 32)
STAGING_OWNER_PW=$(gen 32); STAGING_APP_PW=$(gen 32); STAGING_BACKUP_PW=$(gen 32)
say "Six passwords, one per role per branch. Shown here and nowhere else."
say ""
note "  production (branch main)"
secret_line overload_owner  "$MAIN_OWNER_PW"
secret_line overload_app    "$MAIN_APP_PW"
secret_line overload_backup "$MAIN_BACKUP_PW"
say ""
note "  staging (branch staging)"
secret_line overload_owner  "$STAGING_OWNER_PW"
secret_line overload_app    "$STAGING_APP_PW"
secret_line overload_backup "$STAGING_BACKUP_PW"
say ""
warn "They are not saved to disk. They go into Vercel in stages 11 and 12."
pause "Noted — continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Bootstrap the roles on main"
say "infra/db/bootstrap.sql creates the three roles with no passwords."
open_url "https://console.neon.tech/app/projects"
step "SQL Editor. Set the branch selector to 'main'."
step "Paste the whole of infra/db/bootstrap.sql and run it."
step "Then run these three statements, with the PRODUCTION passwords above:"
say ""
secret_line "ALTER ROLE overload_owner  PASSWORD" "'$MAIN_OWNER_PW';"
secret_line "ALTER ROLE overload_app    PASSWORD" "'$MAIN_APP_PW';"
secret_line "ALTER ROLE overload_backup PASSWORD" "'$MAIN_BACKUP_PW';"
say ""
note "Privileges are not granted here — the first migration does that."
pause "Done on main?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Bootstrap the roles on staging"
warn "Different passwords. Check the branch selector says 'staging'."
step "SQL Editor → branch 'staging' → paste infra/db/bootstrap.sql, run it."
step "Then these three, with the STAGING passwords:"
say ""
secret_line "ALTER ROLE overload_owner  PASSWORD" "'$STAGING_OWNER_PW';"
secret_line "ALTER ROLE overload_app    PASSWORD" "'$STAGING_APP_PW';"
secret_line "ALTER ROLE overload_backup PASSWORD" "'$STAGING_BACKUP_PW';"
pause "Done on staging?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Vercel — two projects, protection off"
open_url "https://vercel.com/new"
say "Import this repository TWICE, as two projects."
say ""
note "  overload-web"
step "Root Directory: apps/web.  Production Branch: main."
step "Do not deploy yet if it offers — there is nothing to build."
say ""
note "  overload-api"
step "Root Directory: apps/api.  Production Branch: main."
step "Settings → Functions → Region: Singapore (sin1)."
say ""
warn "On BOTH projects: Settings → Deployment Protection → None."
note "Standard Protection puts Vercel Authentication in front of every non-"
note "production URL. The server-side rewrite carries no Vercel cookie, Health"
note "Auto Export sends only an ingest token, and the installed-app checklist"
note "would hit a Vercel login. See docs/12 §1."
say ""
step "Copy your Vercel team/account slug from the dashboard URL."
ask VERCEL_SCOPE "team or account slug:"
step "Copy the production domain of overload-web (…vercel.app)."
ask WEB_ORIGIN "web production origin (https://…):"
step "Copy the production domain of overload-api."
ask API_ORIGIN_PROD "api production origin (https://…):"
write_env VERCEL_SCOPE "$VERCEL_SCOPE"
write_env WEB_ORIGIN "$WEB_ORIGIN"
write_env API_ORIGIN_PROD "$API_ORIGIN_PROD"
WEB_STAGING="https://overload-web-git-develop-${VERCEL_SCOPE}.vercel.app"
API_STAGING="https://overload-api-git-develop-${VERCEL_SCOPE}.vercel.app"
say ""
note "Staging URLs will be:"
note "  web  $WEB_STAGING"
note "  api  $API_STAGING"
note "Check them against the dashboard after the first push to develop."
write_env WEB_STAGING "$WEB_STAGING"
write_env API_STAGING "$API_STAGING"
pause "Both projects created and protection set to None?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Google — one OAuth client, three redirect URIs"
open_url "https://console.cloud.google.com/apis/credentials"
step "Create a project (or pick one), then configure the OAuth consent screen:"
note "  User type External, app name Overload, your email as support contact."
note "  Publishing status can stay Testing — add yourself as a test user."
step "Credentials → Create Credentials → OAuth client ID → Web application."
step "Add all three Authorised redirect URIs:"
say ""
note "  ${WEB_ORIGIN}/api/auth/callback/google"
note "  ${WEB_STAGING}/api/auth/callback/google"
note "  http://localhost:5173/api/auth/callback/google"
say ""
warn "All three point at the WEB origin, never the API — Better Auth's baseURL"
warn "is the web origin so the callback returns through the rewrite (docs/03 §5)."
step "Create, then copy the client ID and client secret."
ask GOOGLE_CLIENT_ID "Google client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Google client secret:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
note "The client secret is held in memory only; it goes into Vercel in stage 11."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Sentry — two projects and the monitors"
open_url "https://sentry.io/organizations/new/"
step "Create two projects: 'overload-web' (React) and 'overload-api' (Node)."
step "Copy each project's DSN — both are public by design."
ask SENTRY_DSN_API "api DSN:"
ask VITE_SENTRY_DSN "web DSN:"
step "Settings → Auth Tokens → create one with project:releases scope."
ask_secret SENTRY_AUTH_TOKEN "Sentry auth token:"
write_env SENTRY_DSN_API "$SENTRY_DSN_API"
write_env VITE_SENTRY_DSN "$VITE_SENTRY_DSN"
say ""
say "Two monitors, both production-only (docs/12 §5). Set them up now or after"
say "the first deploy — the endpoints do not exist yet:"
step "Uptime monitor: GET ${API_ORIGIN_PROD}/api/health every 5 minutes, alert"
note "  after 3 consecutive failures."
step "Cron monitor: for the daily job, which checks in at start and finish."
step "Alerts: new issues only, filtered to environment:production."
pause "Continue."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Generate the application secrets"
BETTER_AUTH_SECRET_PROD=$(gen 48); BETTER_AUTH_SECRET_STAGING=$(gen 48)
CRON_SECRET_PROD=$(gen 48);        CRON_SECRET_STAGING=$(gen 48)
say "Session signing and the cron bearer. Different per environment (docs/12 §2)."
say ""
note "  production"
secret_line BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET_PROD"
secret_line CRON_SECRET        "$CRON_SECRET_PROD"
say ""
note "  staging"
secret_line BETTER_AUTH_SECRET "$BETTER_AUTH_SECRET_STAGING"
secret_line CRON_SECRET        "$CRON_SECRET_STAGING"
note "Staging has no cron, but the route still checks the secret."
pause "Noted — continue."

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Vercel variables — overload-api"
ask ADMIN_EMAIL "the admin's Google email:"
ask OFF_CONTACT "contact email for the Open Food Facts User-Agent:"
ask_secret ANTHROPIC_API_KEY "Anthropic API key (Enter to skip until M2):"
write_env ADMIN_EMAIL "$ADMIN_EMAIL"
write_env OFF_CONTACT "$OFF_CONTACT"
open_url "https://vercel.com/${VERCEL_SCOPE}/overload-api/settings/environment-variables"
warn "Mark every value below SECRET except the four marked Config."
warn "Preview values must be scoped to the 'develop' branch, and the same values"
warn "added again unscoped so PR previews match staging (docs/12 §2)."
say ""
note "  PRODUCTION"
secret_line DATABASE_URL          "postgresql://overload_app:${MAIN_APP_PW}@${NEON_MAIN_POOLED_HOST}/${NEON_DB}?sslmode=require"
secret_line DATABASE_URL_DIRECT   "postgresql://overload_owner:${MAIN_OWNER_PW}@${NEON_MAIN_DIRECT_HOST}/${NEON_DB}?sslmode=require"
secret_line BETTER_AUTH_SECRET    "$BETTER_AUTH_SECRET_PROD"
secret_line CRON_SECRET           "$CRON_SECRET_PROD"
secret_line GOOGLE_CLIENT_SECRET  "$GOOGLE_CLIENT_SECRET"
secret_line "SENTRY_AUTH_TOKEN"   "$SENTRY_AUTH_TOKEN"
secret_line "ANTHROPIC_API_KEY"   "${ANTHROPIC_API_KEY:-<add in M2>}"
secret_line "BETTER_AUTH_URL cfg" "$WEB_ORIGIN"
secret_line "GOOGLE_CLIENT_ID cfg" "$GOOGLE_CLIENT_ID"
secret_line "ADMIN_EMAIL cfg"     "$ADMIN_EMAIL"
secret_line "SENTRY_DSN cfg"      "$SENTRY_DSN_API"
secret_line "OFF_CONTACT cfg"     "$OFF_CONTACT"
pause "Production variables saved?"
_clear
printf '\n%s%s▸ Stage %s/%s · Vercel variables — overload-api (preview)%s\n' \
  "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$RESET"
note "  PREVIEW — scoped to branch 'develop', then the same values unscoped"
secret_line DATABASE_URL          "postgresql://overload_app:${STAGING_APP_PW}@${NEON_STAGING_POOLED_HOST}/${NEON_DB}?sslmode=require"
secret_line DATABASE_URL_DIRECT   "postgresql://overload_owner:${STAGING_OWNER_PW}@${NEON_STAGING_DIRECT_HOST}/${NEON_DB}?sslmode=require"
secret_line BETTER_AUTH_SECRET    "$BETTER_AUTH_SECRET_STAGING"
secret_line CRON_SECRET           "$CRON_SECRET_STAGING"
secret_line "BETTER_AUTH_URL cfg" "$WEB_STAGING"
note "  Google, Sentry, Anthropic, ADMIN_EMAIL and OFF_CONTACT are the same as production."
pause "Preview variables saved?"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Vercel variables — overload-web"
open_url "https://vercel.com/${VERCEL_SCOPE}/overload-web/settings/environment-variables"
say "Three variables. Only SENTRY_AUTH_TOKEN is Secret."
say ""
note "  PRODUCTION"
secret_line "API_ORIGIN cfg"       "$API_ORIGIN_PROD"
secret_line "VITE_SENTRY_DSN cfg"  "$VITE_SENTRY_DSN"
secret_line SENTRY_AUTH_TOKEN      "$SENTRY_AUTH_TOKEN"
say ""
note "  PREVIEW — scoped to 'develop', then unscoped"
secret_line "API_ORIGIN cfg"       "$API_STAGING"
note "  VITE_SENTRY_DSN and SENTRY_AUTH_TOKEN are the same as production."
say ""
warn "VITE_ is the only prefix that reaches the browser bundle. Nothing else"
warn "may carry it."
pause "Web variables saved?"

# ── 13 ────────────────────────────────────────────────────────────────────
stage "GitHub — the backup secret"
say "The nightly pg_dump runs in GitHub Actions as overload_backup (docs/13 §2)."
BACKUP_URL="postgresql://overload_backup:${MAIN_BACKUP_PW}@${NEON_MAIN_DIRECT_HOST}/${NEON_DB}?sslmode=require"
set_secret DATABASE_URL_BACKUP "$BACKUP_URL"
note "Direct connection, production branch, read-only role."
note "The S3 bucket and its OIDC role are separate, and are on the 'before M1"
note "ships' list in docs/13 §9 — not needed for slice 1."
pause "Continue."

# ── 14 ────────────────────────────────────────────────────────────────────
stage "Local development"
say "Local never touches Neon. Docker Postgres runs bootstrap.sql and then"
say "infra/db/local-passwords.sql from docker-entrypoint-initdb.d."
say ""
step "Once apps/api and apps/web exist, create their gitignored .env.local:"
say ""
note "  apps/api/.env.local"
note "    DATABASE_URL=postgresql://overload_app:overload_app_dev@localhost:5432/overload"
note "    DATABASE_URL_DIRECT=postgresql://overload_owner:overload_owner_dev@localhost:5432/overload"
note "    BETTER_AUTH_URL=http://localhost:5173"
note "    BETTER_AUTH_SECRET=<any long string, local only>"
note "    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}"
note "    GOOGLE_CLIENT_SECRET=<the one from stage 8>"
note "    ADMIN_EMAIL=${ADMIN_EMAIL}"
note "    CRON_SECRET=<any long string, local only>"
say ""
note "  apps/web/.env.local"
note "    API_ORIGIN=http://localhost:8787"
say ""
step "docker compose up -d, then dbmate --migrations-dir apps/api/migrations migrate"
pause "Continue."

finish
printf '  %sWhat is still open%s\n' "$BOLD" "$RESET"
note "  · Deployment Protection — confirm it reads None on BOTH projects"
note "  · the staging branch URLs, checked against the dashboard after the"
note "    first push to develop"
note "  · a Neon restore-from-history rehearsal on staging (docs/12 §6)"
note "  · dbmate inside Vercel's build image — proven by slice 1's first deploy"
note "  · docs/11 §3 items 1 and 2 on a real iPhone"
printf '\n'
note "  .provision.local holds the non-secret values only. Delete it when done."
printf '\n'
