#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

ENV_FILE=".provision.local"

WEB_ORIGIN="https://overload-web-pied.vercel.app"
API_ORIGIN_PROD="https://overload-api-mu.vercel.app"
VERCEL_SCOPE="yuta-asakuras-projects"
WEB_STAGING="https://overload-web-git-develop-${VERCEL_SCOPE}.vercel.app"
API_STAGING="https://overload-api-git-develop-${VERCEL_SCOPE}.vercel.app"

gen() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-32}"; printf '\n'; }
secret_line() { printf '    %s%-24s%s %s\n' "$BOLD" "$1" "$RESET" "$2"; }

# vercel_env PROJECT JSON — push variables through the Vercel API.
vercel_env() {
  local project="$1" vars="$2"
  printf '{"project":"%s","vars":%s}' "$project" "$vars" | node scripts/vercel-env.mjs || {
    SKIPPED+=("Vercel variables for $project — set them by hand in the dashboard")
    warn "could not set $project variables automatically"
  }
}

banner "Overload — finish provisioning"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Where we are"
say "Already done, and not repeated here:"
note "  · Neon project, branch 'main', branch 'staging' (branched first)"
note "  · the three roles created on both branches"
note "  · both Vercel projects, Deployment Protection None, api in sin1"
say ""
say "This script does the rest — and unlike the first one, it writes the Vercel"
say "variables for you through the API instead of making you paste 17 values."
say ""
warn "It starts by rotating the six database passwords."
note "The originals were printed once and cleared, and the three production ones"
note "were pasted into a chat transcript. Rotating is not optional."
say ""
if [[ ! -f scripts/vercel-env.mjs ]]; then
  warn "run this from the repo root: bash scripts/provision-resume.sh"
  exit 1
fi
command -v node >/dev/null 2>&1 || { warn "node is required"; exit 1; }
if ! npx --yes vercel@latest whoami >/dev/null 2>&1; then
  warn "Vercel CLI auth expired. Run 'npx vercel login', then restart this script."
  exit 1
fi
note "Vercel auth OK."
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Rotate the database passwords"
MAIN_OWNER_PW=$(gen 32);    MAIN_APP_PW=$(gen 32);    MAIN_BACKUP_PW=$(gen 32)
STAGING_OWNER_PW=$(gen 32); STAGING_APP_PW=$(gen 32); STAGING_BACKUP_PW=$(gen 32)
open_url "https://console.neon.tech/app/projects"
step "SQL Editor. Branch selector on 'main'. Run these three:"
say ""
secret_line "ALTER ROLE overload_owner  PASSWORD" "'$MAIN_OWNER_PW';"
secret_line "ALTER ROLE overload_app    PASSWORD" "'$MAIN_APP_PW';"
secret_line "ALTER ROLE overload_backup PASSWORD" "'$MAIN_BACKUP_PW';"
say ""
pause "Done on main?"
_clear
printf '\n%s%s▸ Stage %s/%s · Rotate the database passwords (staging)%s\n' \
  "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$RESET"
warn "Switch the branch selector to 'staging'. Different passwords."
say ""
secret_line "ALTER ROLE overload_owner  PASSWORD" "'$STAGING_OWNER_PW';"
secret_line "ALTER ROLE overload_app    PASSWORD" "'$STAGING_APP_PW';"
secret_line "ALTER ROLE overload_backup PASSWORD" "'$STAGING_BACKUP_PW';"
say ""
note "You never need to copy these anywhere else — stages 6-8 send them to"
note "Vercel and GitHub for you."
pause "Done on staging?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google — one OAuth client, three redirect URIs"
open_url "https://console.cloud.google.com/apis/credentials"
step "Create a project if you have none, then the OAuth consent screen:"
note "  External, app name Overload, your email as support contact."
note "  Leave publishing status Testing and add yourself as a test user."
step "Credentials → Create Credentials → OAuth client ID → Web application."
step "Add all three Authorised redirect URIs, exactly:"
say ""
note "  ${WEB_ORIGIN}/api/auth/callback/google"
note "  ${WEB_STAGING}/api/auth/callback/google"
note "  http://localhost:5173/api/auth/callback/google"
say ""
warn "All three point at the WEB origin, never the API. Better Auth's baseURL is"
warn "the web origin so the callback returns through the rewrite (docs/03 §5)."
step "Create, then copy both values."
ask GOOGLE_CLIENT_ID "Google client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Google client secret:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Sentry — two projects"
open_url "https://sentry.io/"
step "Create two projects: 'overload-web' (React) and 'overload-api' (Node)."
step "Copy each DSN. Both are public by design."
ask SENTRY_DSN_API "api DSN:"
ask VITE_SENTRY_DSN "web DSN:"
step "Settings → Auth Tokens → new token with project:releases scope."
ask_secret SENTRY_AUTH_TOKEN "Sentry auth token:"
write_env SENTRY_DSN_API "$SENTRY_DSN_API"
write_env VITE_SENTRY_DSN "$VITE_SENTRY_DSN"
note "The two monitors in docs/12 §5 are set up after slice 1 deploys — the"
note "/api/health route does not exist yet."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The last few values"
ask ADMIN_EMAIL "the admin's Google email:"
ask OFF_CONTACT "contact email for the Open Food Facts User-Agent:"
ask_secret ANTHROPIC_API_KEY "Anthropic API key (Enter to skip until M2):"
write_env ADMIN_EMAIL "$ADMIN_EMAIL"
write_env OFF_CONTACT "$OFF_CONTACT"
BETTER_AUTH_SECRET_PROD=$(gen 48); BETTER_AUTH_SECRET_STAGING=$(gen 48)
CRON_SECRET_PROD=$(gen 48);        CRON_SECRET_STAGING=$(gen 48)
note "Session signing and cron secrets generated, different per environment."
pause "Continue — the next three stages run by themselves."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Writing overload-api variables — production"
DB_URL_PROD="postgresql://overload_app:${MAIN_APP_PW}@${NEON_MAIN_POOLED_HOST}.ap-southeast-1.aws.neon.tech/${NEON_DB}?sslmode=require"
DB_DIRECT_PROD="postgresql://overload_owner:${MAIN_OWNER_PW}@${NEON_MAIN_DIRECT_HOST}.ap-southeast-1.aws.neon.tech/${NEON_DB}?sslmode=require"
vercel_env overload-api "$(node -e '
const a = process.argv.slice(1);
const [db, dbd, bas, cron, gid, gsec, admin, dsn, off, anth, tok, authurl] = a;
const S = (key, value) => ({ key, value, type: "sensitive", target: "production" });
const P = (key, value) => ({ key, value, type: "plain", target: "production" });
console.log(JSON.stringify([
  S("DATABASE_URL", db), S("DATABASE_URL_DIRECT", dbd),
  S("BETTER_AUTH_SECRET", bas), S("CRON_SECRET", cron),
  S("GOOGLE_CLIENT_SECRET", gsec), S("SENTRY_AUTH_TOKEN", tok),
  S("ANTHROPIC_API_KEY", anth),
  P("BETTER_AUTH_URL", authurl), P("GOOGLE_CLIENT_ID", gid),
  P("ADMIN_EMAIL", admin), P("SENTRY_DSN", dsn), P("OFF_CONTACT", off),
]));
' "$DB_URL_PROD" "$DB_DIRECT_PROD" "$BETTER_AUTH_SECRET_PROD" "$CRON_SECRET_PROD" \
  "$GOOGLE_CLIENT_ID" "$GOOGLE_CLIENT_SECRET" "$ADMIN_EMAIL" "$SENTRY_DSN_API" \
  "$OFF_CONTACT" "${ANTHROPIC_API_KEY:-}" "$SENTRY_AUTH_TOKEN" "$WEB_ORIGIN")"
pause "Continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Writing overload-api variables — preview (staging)"
DB_URL_STG="postgresql://overload_app:${STAGING_APP_PW}@${NEON_STAGING_POOLED_HOST}.ap-southeast-1.aws.neon.tech/${NEON_DB}?sslmode=require"
DB_DIRECT_STG="postgresql://overload_owner:${STAGING_OWNER_PW}@${NEON_STAGING_DIRECT_HOST}.ap-southeast-1.aws.neon.tech/${NEON_DB}?sslmode=require"
say "Each value is written twice: scoped to branch 'develop', and unscoped so PR"
say "previews match staging (docs/12 §2)."
vercel_env overload-api "$(node -e '
const a = process.argv.slice(1);
const [db, dbd, bas, cron, gid, gsec, admin, dsn, off, anth, tok, authurl] = a;
const out = [];
const add = (key, value, type) => {
  out.push({ key, value, type, target: "preview", gitBranch: "develop" });
  out.push({ key, value, type, target: "preview" });
};
add("DATABASE_URL", db, "sensitive"); add("DATABASE_URL_DIRECT", dbd, "sensitive");
add("BETTER_AUTH_SECRET", bas, "sensitive"); add("CRON_SECRET", cron, "sensitive");
add("GOOGLE_CLIENT_SECRET", gsec, "sensitive"); add("SENTRY_AUTH_TOKEN", tok, "sensitive");
add("ANTHROPIC_API_KEY", anth, "sensitive");
add("BETTER_AUTH_URL", authurl, "plain"); add("GOOGLE_CLIENT_ID", gid, "plain");
add("ADMIN_EMAIL", admin, "plain"); add("SENTRY_DSN", dsn, "plain");
add("OFF_CONTACT", off, "plain");
console.log(JSON.stringify(out));
' "$DB_URL_STG" "$DB_DIRECT_STG" "$BETTER_AUTH_SECRET_STAGING" "$CRON_SECRET_STAGING" \
  "$GOOGLE_CLIENT_ID" "$GOOGLE_CLIENT_SECRET" "$ADMIN_EMAIL" "$SENTRY_DSN_API" \
  "$OFF_CONTACT" "${ANTHROPIC_API_KEY:-}" "$SENTRY_AUTH_TOKEN" "$WEB_STAGING")"
pause "Continue."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Writing overload-web variables"
vercel_env overload-web "$(node -e '
const [apiProd, apiStg, dsn, tok] = process.argv.slice(1);
const out = [
  { key: "API_ORIGIN", value: apiProd, type: "plain", target: "production" },
  { key: "VITE_SENTRY_DSN", value: dsn, type: "plain", target: "production" },
  { key: "SENTRY_AUTH_TOKEN", value: tok, type: "sensitive", target: "production" },
];
for (const branch of ["develop", null]) {
  const g = branch ? { gitBranch: branch } : {};
  out.push({ key: "API_ORIGIN", value: apiStg, type: "plain", target: "preview", ...g });
  out.push({ key: "VITE_SENTRY_DSN", value: dsn, type: "plain", target: "preview", ...g });
  out.push({ key: "SENTRY_AUTH_TOKEN", value: tok, type: "sensitive", target: "preview", ...g });
}
console.log(JSON.stringify(out));
' "$API_ORIGIN_PROD" "$API_STAGING" "$VITE_SENTRY_DSN" "$SENTRY_AUTH_TOKEN")"
warn "VITE_ is the only prefix that reaches the browser bundle."
pause "Continue."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "GitHub secret, and local development"
BACKUP_URL="postgresql://overload_backup:${MAIN_BACKUP_PW}@${NEON_MAIN_DIRECT_HOST}.ap-southeast-1.aws.neon.tech/${NEON_DB}?sslmode=require"
set_secret DATABASE_URL_BACKUP "$BACKUP_URL"
note "Direct connection, production branch, read-only role (docs/13 §2)."
say ""
say "Local never touches Neon. Once apps/api and apps/web exist:"
note "  apps/api/.env.local"
note "    DATABASE_URL=postgresql://overload_app:overload_app_dev@localhost:5432/overload"
note "    DATABASE_URL_DIRECT=postgresql://overload_owner:overload_owner_dev@localhost:5432/overload"
note "    BETTER_AUTH_URL=http://localhost:5173"
note "    BETTER_AUTH_SECRET=<any long string>"
note "    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}"
note "    GOOGLE_CLIENT_SECRET=<the one from stage 3>"
note "    ADMIN_EMAIL=${ADMIN_EMAIL}"
note "    CRON_SECRET=<any long string>"
note "  apps/web/.env.local"
note "    API_ORIGIN=http://localhost:8787"
pause "Continue."

finish
printf '  %sStill open%s\n' "$BOLD" "$RESET"
note "  · Sentry uptime and cron monitors — after slice 1 deploys"
note "  · a Neon restore-from-history rehearsal on staging (docs/12 §6)"
note "  · docs/11 §3 items 1 and 2 on a real iPhone"
note "  · the staging branch URLs, confirmed against the dashboard"
printf '\n'
note "  Delete .provision.local when you are done. It holds no secrets."
printf '\n'
