#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE=".provision.local"

# No screen clearing: an earlier version cleared between stages and hid the
# errors from the Vercel writes, which is why none of them landed.
_clear() { :; }

WEB_ORIGIN="https://overload-web-pied.vercel.app"
API_ORIGIN_PROD="https://overload-api-mu.vercel.app"
VERCEL_SCOPE="yuta-asakuras-projects"
WEB_STAGING="https://overload-web-git-develop-${VERCEL_SCOPE}.vercel.app"
API_STAGING="https://overload-api-git-develop-${VERCEL_SCOPE}.vercel.app"
NEON_SUFFIX=".ap-southeast-1.aws.neon.tech"

gen() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-32}"; printf '\n'; }
sql() { printf '    %sALTER ROLE %-17s PASSWORD %s'"'"'%s'"'"';\n' "$BOLD" "$1" "$RESET" "$2"; }

banner "Overload — Google, the database passwords, and every Vercel variable"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before we start"
say "Order matters here, and it is the opposite of the last version:"
note "  Google first, database passwords second."
say ""
say "The reason: a Google client secret is shown once and can never be read"
say "again, so fetching it mid-run is what tempted a restart — and a restart"
say "after the rotation means six more ALTER ROLE pastes. Nothing in stage 2"
say "changes any existing state, so abandoning it costs nothing."
say ""
for f in scripts/vercel-env.mjs scripts/vercel-verify.mjs .provision.local; do
  [[ -f "$f" ]] || { warn "missing $f — run this from the repo root"; exit 1; }
done
# shellcheck disable=SC1091
set -a; . ./.provision.local; set +a
: "${NEON_MAIN_POOLED_HOST:?not in .provision.local}"
: "${NEON_STAGING_POOLED_HOST:?not in .provision.local}"
: "${ADMIN_EMAIL:?not in .provision.local}"
note "hosts, admin email and OFF contact read from .provision.local"
if ! npx --yes vercel@latest whoami >/dev/null 2>&1; then
  warn "Vercel auth expired. Run 'npx vercel login', then start this script again."
  exit 1
fi
note "Vercel auth OK"
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google — a new OAuth client"
say "Google shows a client secret once, at creation, and has no way to add a"
say "second secret to an existing client. A lost secret therefore means a new"
say "client, not a recovered one."
say ""
open_url "https://console.cloud.google.com/apis/credentials"
step "Credentials → Create Credentials → OAuth client ID → Web application."
step "Name it something you will recognise, e.g. 'Overload web'."
step "Add all three Authorised redirect URIs, exactly:"
say ""
note "  ${WEB_ORIGIN}/api/auth/callback/google"
note "  ${WEB_STAGING}/api/auth/callback/google"
note "  http://localhost:5173/api/auth/callback/google"
say ""
warn "All three point at the WEB origin, never the API. Better Auth's baseURL is"
warn "the web origin, so the callback returns through the rewrite (docs/03 §5)."
say ""
step "Create. Copy BOTH values off the dialog before closing it."
warn "Do not close that dialog until you have pasted the secret below."
ask GOOGLE_CLIENT_ID "Google client ID:"
[[ -n "$GOOGLE_CLIENT_ID" ]] || { warn "required — nothing has changed, just start again"; exit 1; }
ask_secret GOOGLE_CLIENT_SECRET "Google client secret:"
[[ -n "$GOOGLE_CLIENT_SECRET" ]] || { warn "required — nothing has changed, just start again"; exit 1; }
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
ask_secret ANTHROPIC_API_KEY "Anthropic API key (Enter to skip until M2):"
say ""
note "Delete the old OAuth client in Google once sign-in works on staging."
note "Sentry stays unset: the sentry-cli login token is scoped org:ci and cannot"
note "create projects. Create the projects whenever, then re-run this — it upserts."
pause "Continue to the database passwords?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Rotate the six database passwords"
MAIN_OWNER_PW=$(gen 32);    MAIN_APP_PW=$(gen 32);    MAIN_BACKUP_PW=$(gen 32)
STAGING_OWNER_PW=$(gen 32); STAGING_APP_PW=$(gen 32); STAGING_BACKUP_PW=$(gen 32)
BETTER_AUTH_SECRET_PROD=$(gen 48); BETTER_AUTH_SECRET_STAGING=$(gen 48)
CRON_SECRET_PROD=$(gen 48);        CRON_SECRET_STAGING=$(gen 48)
warn "From here on, do not restart — these passwords exist only in this terminal"
warn "until stage 4 writes them to Vercel."
open_url "https://console.neon.tech/app/projects"
say ""
step "SQL Editor, branch selector on 'main'. Run these three:"
say ""
sql overload_owner  "$MAIN_OWNER_PW"
sql overload_app    "$MAIN_APP_PW"
sql overload_backup "$MAIN_BACKUP_PW"
say ""
pause "Run them on main, then press Enter."
say ""
step "Switch the branch selector to 'staging'. Run these three:"
say ""
sql overload_owner  "$STAGING_OWNER_PW"
sql overload_app    "$STAGING_APP_PW"
sql overload_backup "$STAGING_BACKUP_PW"
say ""
pause "Run them on staging, then press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Write everything, then read it back"
export V_DB_PROD="postgresql://overload_app:${MAIN_APP_PW}@${NEON_MAIN_POOLED_HOST}${NEON_SUFFIX}/${NEON_DB}?sslmode=require"
export V_DBD_PROD="postgresql://overload_owner:${MAIN_OWNER_PW}@${NEON_MAIN_DIRECT_HOST}${NEON_SUFFIX}/${NEON_DB}?sslmode=require"
export V_DB_STG="postgresql://overload_app:${STAGING_APP_PW}@${NEON_STAGING_POOLED_HOST}${NEON_SUFFIX}/${NEON_DB}?sslmode=require"
export V_DBD_STG="postgresql://overload_owner:${STAGING_OWNER_PW}@${NEON_STAGING_DIRECT_HOST}${NEON_SUFFIX}/${NEON_DB}?sslmode=require"
export V_BAS_PROD="$BETTER_AUTH_SECRET_PROD" V_BAS_STG="$BETTER_AUTH_SECRET_STAGING"
export V_CRON_PROD="$CRON_SECRET_PROD" V_CRON_STG="$CRON_SECRET_STAGING"
export V_GID="$GOOGLE_CLIENT_ID" V_GSEC="$GOOGLE_CLIENT_SECRET"
export V_ADMIN="$ADMIN_EMAIL" V_OFF="${OFF_CONTACT:-$ADMIN_EMAIL}" V_ANTH="${ANTHROPIC_API_KEY:-}"
export V_WEB="$WEB_ORIGIN" V_WEB_STG="$WEB_STAGING"
export V_API="$API_ORIGIN_PROD" V_API_STG="$API_STAGING"

say "overload-api:"
node -e '
const E = process.env;
const out = [];
const prod = (key, value, type) => out.push({ key, value, type, target: "production" });
const prev = (key, value, type) => {
  out.push({ key, value, type, target: "preview", gitBranch: "develop" });
  out.push({ key, value, type, target: "preview" });
};
prod("DATABASE_URL", E.V_DB_PROD, "sensitive");
prod("DATABASE_URL_DIRECT", E.V_DBD_PROD, "sensitive");
prod("BETTER_AUTH_SECRET", E.V_BAS_PROD, "sensitive");
prod("CRON_SECRET", E.V_CRON_PROD, "sensitive");
prod("BETTER_AUTH_URL", E.V_WEB, "plain");
prev("DATABASE_URL", E.V_DB_STG, "sensitive");
prev("DATABASE_URL_DIRECT", E.V_DBD_STG, "sensitive");
prev("BETTER_AUTH_SECRET", E.V_BAS_STG, "sensitive");
prev("CRON_SECRET", E.V_CRON_STG, "sensitive");
prev("BETTER_AUTH_URL", E.V_WEB_STG, "plain");
for (const [k, v, t] of [
  ["GOOGLE_CLIENT_SECRET", E.V_GSEC, "sensitive"],
  ["ANTHROPIC_API_KEY", E.V_ANTH, "sensitive"],
  ["GOOGLE_CLIENT_ID", E.V_GID, "plain"],
  ["ADMIN_EMAIL", E.V_ADMIN, "plain"],
  ["OFF_CONTACT", E.V_OFF, "plain"],
]) { prod(k, v, t); prev(k, v, t); }
console.log(JSON.stringify({ project: "overload-api", vars: out }));
' | node scripts/vercel-env.mjs || SKIPPED+=("overload-api variables")

say ""
say "overload-web:"
node -e '
const E = process.env;
const out = [{ key: "API_ORIGIN", value: E.V_API, type: "plain", target: "production" }];
for (const b of ["develop", null]) {
  const g = b ? { gitBranch: b } : {};
  out.push({ key: "API_ORIGIN", value: E.V_API_STG, type: "plain", target: "preview", ...g });
}
console.log(JSON.stringify({ project: "overload-web", vars: out }));
' | node scripts/vercel-env.mjs || SKIPPED+=("overload-web variables")

say ""
say "GitHub:"
set_secret DATABASE_URL_BACKUP \
  "postgresql://overload_backup:${MAIN_BACKUP_PW}@${NEON_MAIN_DIRECT_HOST}${NEON_SUFFIX}/${NEON_DB}?sslmode=require"

say ""
say "Reading Vercel back:"
node scripts/vercel-verify.mjs || warn "verification found gaps — see above, and re-run this script"

finish
note "Sentry's variables are the only ones deliberately unset."
note "Delete the old Google OAuth client once sign-in works on staging."
printf '\n'
