// The seeded exercise library (S8), hand-written (docs/06, 2026-09-23: no dataset carries an
// increment, a rest default or a rep range, and the permissive ones have bad provenance).
//
// `pnpm --filter @overload/api seed:exercises` writes the seed migration from this list. The
// migration is what ships; this file is its source. After the migration has run anywhere, a
// correction is a new migration, not an edit here.
//
// Names: specification → equipment → exercise ("Incline Dumbbell Bench Press", CONTEXT.md).
// Bodyweight movements carry no equipment word. Increments per equipment class (docs/04):
// barbell 2.5 · dumbbell 1.0 · machine_plate 2.5 · machine_stack 5.0 · cable 2.5 · bodyweight 0.
// Defaults: 6–10 reps and 120 s rest (S3, S5). The heavy barbell lifts rest 180 s; isolation
// work is 10–15 reps with 90 s.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

type Equipment =
  | 'barbell'
  | 'dumbbell'
  | 'machine_plate'
  | 'machine_stack'
  | 'cable'
  | 'bodyweight';
type Kind = 'heavy' | 'compound' | 'isolation';

const increments: Record<Equipment, number> = {
  barbell: 2.5,
  dumbbell: 1.0,
  machine_plate: 2.5,
  machine_stack: 5.0,
  cable: 2.5,
  bodyweight: 0,
};

const defaults: Record<Kind, { rest: number; repLow: number; repHigh: number }> = {
  heavy: { rest: 180, repLow: 6, repHigh: 10 },
  compound: { rest: 120, repLow: 6, repHigh: 10 },
  isolation: { rest: 90, repLow: 10, repHigh: 15 },
};

const exercises: [name: string, equipment: Equipment, kind: Kind][] = [
  ['Barbell Back Squat', 'barbell', 'heavy'],
  ['Barbell Front Squat', 'barbell', 'heavy'],
  ['Barbell Deadlift', 'barbell', 'heavy'],
  ['Barbell Romanian Deadlift', 'barbell', 'heavy'],
  ['Barbell Bench Press', 'barbell', 'heavy'],
  ['Incline Barbell Bench Press', 'barbell', 'heavy'],
  ['Close Grip Barbell Bench Press', 'barbell', 'compound'],
  ['Barbell Overhead Press', 'barbell', 'heavy'],
  ['Bent Over Barbell Row', 'barbell', 'heavy'],
  ['Barbell Hip Thrust', 'barbell', 'compound'],
  ['Barbell Curl', 'barbell', 'isolation'],
  ['Lying EZ Bar Triceps Extension', 'barbell', 'isolation'],

  ['Dumbbell Bench Press', 'dumbbell', 'compound'],
  ['Incline Dumbbell Bench Press', 'dumbbell', 'compound'],
  ['Seated Dumbbell Shoulder Press', 'dumbbell', 'compound'],
  ['1 Arm Dumbbell Row', 'dumbbell', 'compound'],
  ['Dumbbell Romanian Deadlift', 'dumbbell', 'compound'],
  ['Walking Dumbbell Lunge', 'dumbbell', 'compound'],
  ['Bulgarian Dumbbell Split Squat', 'dumbbell', 'compound'],
  ['Dumbbell Goblet Squat', 'dumbbell', 'compound'],
  ['Dumbbell Lateral Raise', 'dumbbell', 'isolation'],
  ['Dumbbell Rear Delt Fly', 'dumbbell', 'isolation'],
  ['Dumbbell Fly', 'dumbbell', 'isolation'],
  ['Dumbbell Curl', 'dumbbell', 'isolation'],
  ['Dumbbell Hammer Curl', 'dumbbell', 'isolation'],
  ['Overhead Dumbbell Triceps Extension', 'dumbbell', 'isolation'],

  ['Machine Chest Press', 'machine_stack', 'compound'],
  ['Machine Shoulder Press', 'machine_stack', 'compound'],
  ['Chest Supported Machine Row', 'machine_stack', 'compound'],
  ['Machine Chest Fly', 'machine_stack', 'isolation'],
  ['Machine Rear Delt Fly', 'machine_stack', 'isolation'],
  ['Machine Leg Extension', 'machine_stack', 'isolation'],
  ['Seated Machine Leg Curl', 'machine_stack', 'isolation'],
  ['Lying Machine Leg Curl', 'machine_stack', 'isolation'],

  ['Plate-Loaded Leg Press', 'machine_plate', 'compound'],
  ['Plate-Loaded Hack Squat', 'machine_plate', 'compound'],
  ['Plate-Loaded Chest Press', 'machine_plate', 'compound'],
  ['Plate-Loaded Row', 'machine_plate', 'compound'],
  ['Standing Plate-Loaded Calf Raise', 'machine_plate', 'isolation'],

  ['Cable Lat Pulldown', 'cable', 'compound'],
  ['Seated Cable Row', 'cable', 'compound'],
  ['Cable Triceps Pushdown', 'cable', 'isolation'],
  ['Overhead Cable Triceps Extension', 'cable', 'isolation'],
  ['1 Arm Cable Lateral Raise', 'cable', 'isolation'],
  ['Cable Face Pull', 'cable', 'isolation'],
  ['Cable Chest Fly', 'cable', 'isolation'],

  ['Pull-Up', 'bodyweight', 'compound'],
  ['Chin-Up', 'bodyweight', 'compound'],
  ['Parallel Bar Dip', 'bodyweight', 'compound'],
  ['Hanging Leg Raise', 'bodyweight', 'isolation'],
];

const quote = (text: string) => `'${text.replaceAll("'", "''")}'`;

export function seedMigration(): string {
  const rows = exercises.map(([name, equipment, kind]) => {
    const d = defaults[kind];
    const increment = increments[equipment].toFixed(2);
    return `  (${quote(name)}, ${quote(equipment)}, ${increment}, ${d.rest}, ${d.repLow}, ${d.repHigh})`;
  });
  return [
    '-- Generated by apps/api/seed/exercises.ts. Do not edit by hand; a correction is a new migration.',
    '-- Custom migration (docs/12 §3): drizzle-kit made the empty file and its journal entry.',
    '',
    'INSERT INTO exercise',
    '  (name, equipment, default_increment_kg, default_rest_seconds, default_rep_low, default_rep_high)',
    'VALUES',
    `${rows.join(',\n')};`,
    '',
  ].join('\n');
}

export const seedMigrationPath = fileURLToPath(
  new URL('../migrations/0003_seed_exercises.sql', import.meta.url),
);

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(seedMigrationPath, seedMigration());
}
